datadog:
  build: dd-agent
  links:
    - web
    - loadbalancer
  environment:
    - API_KEY
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc/mounts:/host/proc/mounts:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  ports:
    - "8125:8125"
  command: dd-agent foreground

web:
  build: web
  ports:
    - "80"
  environment: 
    SERVICE_80_NAME: http
    SERVICE_NAME: app

loadbalancer:
  build: loadbalancer
  ports:
    - "80:80"
  links:
    - web
    - consul

consul:
  command: -server -bootstrap-expect 1
  image: progrium/consul:latest
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  links:
    - web

registrator:
  command: consul://consul:8500
  image: progrium/registrator:latest
  links:
    - consul
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
